// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgwW5xuRGgbBGokMIWP1OiW7kivavaxnE',
    appId: '1:17639018426:web:9953a48e5acea5e3a95783',
    messagingSenderId: '17639018426',
    projectId: 'health-routine-coach-66649',
    authDomain: 'health-routine-coach-66649.firebaseapp.com',
    storageBucket: 'health-routine-coach-66649.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDoypaLtAcXPCl8LpVn0MqYVivr_J_XhI',
    appId: '1:17639018426:android:ae1c961950bc42faa95783',
    messagingSenderId: '17639018426',
    projectId: 'health-routine-coach-66649',
    storageBucket: 'health-routine-coach-66649.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYC6GNu1QDmANYrD-dOCyUHeFl3S7muG0',
    appId: '1:17639018426:ios:f6737160e6af77a1a95783',
    messagingSenderId: '17639018426',
    projectId: 'health-routine-coach-66649',
    storageBucket: 'health-routine-coach-66649.firebasestorage.app',
    iosBundleId: 'com.example.healthRoutineCoach',
  );
}
